home_data:
  description: "Папка со всеми сайтами, находящимися на сервере MihanentalpoFirst"
  dest: {host: backuper@terrarian, path: /home/backuper/backup/machines/mihanlenovo/home/data}
  exclude: [data/root_fs_pre_reinst.fsa]
  src: {host: '', path: /home/data}
home_mihanentalpo:
  dest: {host: backuper@terrarian, path: /home/backuper/backup/machines/mihanlenovo/home/mihanentalpo}
  exclude: [mihanentalpo/Torrents, mihanentalpo/Music, mihanentalpo/.cache, mihanentalpo/.PyCharm40/system/caches,
    mihanentalpo/.PyCharm50/system/caches, mihanentalpo/.PyCharm50/system/LocalHistory,
    mihanentalpo/.xsession-errorsmihanentalpo/.PyCharm40/system/index, mihanentalpo/.PyCharm40/system/log,
    mihanentalpo/.PyCharm50/system/index, mihanentalpo/.PyCharm50/system/log, mihanentalpo/.thumbnails,
    mihanentalpo/Downloads, mihanentalpo/VirtualBox VMs, mihanentalpo/.PyCharm40/system/index,
    mihanentalpo/.TelegramDesktop/log.txt, "mihanentalpo/.config/freshwrapper-data/Shockwave Flash",
    mihanentalpo/.config/transmission/resume, '*.pyc', '*.bak', mihanentalpo/.PyCharm50/system,
    mihanentalpo/.config/google-chrome/Default/Local Storage, mihanentalpo/.config/google-chrome/Default/IndexedDB,
    mihanentalpo/.config/google-chrome/Default/GPUCache, .parentlock, cookies.sqlite,
    downloads.json, mihanentalpo/.icedove/6xzgf26z.default/logs/irc, mihanentalpo/.kde/share/apps/RecentDocuments,
    mihanentalpo/.kde/share/apps/dolphin/view_properties/search, mihanentalpo/.netbeans/8.0.2/var/filehistory,
    mihanentalpo/.PyCharm50/config/options/statistics.application.usages.xml,
    mihanentalpo/git/UnrealEngine, mihanentalpo/UnrealProjects/UnrealZV/.git]
  src: {host: '', path: /home/mihanentalpo}
home_mihanentalpo_downloads:
  dest: {host: backuper@terrarian, path: /home/backuper/backup/machines/mihanlenovo/home/mihanentalpo_Downloads}
  exclude: []
  src: {host: '', path: /home/mihanentalpo/Downloads}
home_mihanentalpo_music:
  dest: {host: backuper@terrarian, path: /home/backuper/backup/machines/mihanlenovo/home/mihanentalpo_Music}
  exclude: []
  src: {host: '', path: /home/mihanentalpo/Music}
home_mihanentalpo_torrents:
  dest: {host: backuper@terrarian, path: /home/backuper/backup/machines/mihanlenovo/home/mihanentalpo_Torrents}
  exclude: []
  src: {host: '', path: /home/mihanentalpo/Torrents}
home_mihanentalpo_vboxvms:
  dest: {host: backuper@terrarian, path: /home/backuper/backup/machines/mihanlenovo/home/mihanentalpo_VirtualBox_VMs}
  exclude: [Logs, '*.log.*', '*.log']
  src: {host: '', path: /home/mihanentalpo/VirtualBox VMs}
local_mysql:
  dest: {host: backuper@terrarian, path: /home/backuper/backup/machines/mihanlenovo/mysql_backup}
  mysqldump:
    filters:
    - [include, '*', '*']
    folder: /home/var/mysql-backup
    password: 123mihan
    sshhost: ''
    user: root
  src: {host: '', path: /home/var/mysql-backup}
var_lib:
  dest: {host: backuper@terrarian, path: /home/backuper/backup/machines/mihanlenovo/var_lib}
  exclude: ['*.tar.gz', '*.zip', '*.sql', '*.tar', '*.log', '*~']
  src: {host: '', path: /home/var/lib}
var_www:
  dest: {host: backuper@terrarian, path: /home/backuper/backup/machines/mihanlenovo/var_www}
  exclude: ['*.tar.gz', '*.zip', '*.sql', '*.tar', '*.log', '*~']
  src: {host: '', path: /home/var/www}
